# .github/workflows/chromatic.yml
# name of our action
name: 'Chromatic Deployment'
#  event that will trigger the action
on: 'push'

# what the action will do
jobs: 
  test:
    runs-on: ubuntu-latest
    # lsit of steps action wll go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
      with:
        projectToken: ${{secrets.CHROMATIC_PROJECT_TOKEN}}
        token: ${{secrets.GITHUB_TOKEN}}

